### ISSUE TITLE
All edited tiles are overwritten with a certain tile when saving

### ISSUE THREAD

**Issue by ghost** [SpaiR/StrongDMM#11] opened 2019-09-15 19:33 UTC
I have had this particular issue happen twice. After working on the map for hours, I close all the other maps I am using for reference and then hit save all. When I open StrongDMM again, all of the tiles that I put objects on are overwritten with one particular tile I had edited earlier (I am not certain what determines the tile). It acts as if it is copy/pasted. Posted is a relevant image. 
![image](https://user-images.githubusercontent.com/48036854/64926668-1fe75580-d7ce-11e9-8e9e-b2e7493ed2a5.png)

**Comment by SpaiR** [comment] 2019-09-16 05:26
I'm sorry for your lost progress. Guys have already reported that kind of issue. So I was assured that the problem is solved.
Could you please doulbe check you're using the latest version? (Help->About, you should find there `Version: 0.0.10`)
If you are, then, if it's possible, send here your file with a corrupted content. I have an assumption where the problem could be, but the real example will simplify the process.

**Comment by CAPTTLasky** [comment] 2019-09-23 19:19
I don't have a Help tab which leads me to believe that I'm not on 0.0.10, but I know for certain that I ran the installer all the way through. So if it didn't update, there might be an issue with the installer. Here is the map file in case you can deduce anything from it.

[ZetaStationBug.zip](https://github.com/SpaiR/StrongDMM/files/3643747/ZetaStationBug.zip)

**Comment by SpaiR** [comment] 2019-09-23 19:45
If you don't have the help button (example below), that means that the problem is with the version you are using for sure. I've added it in 0.0.5 release and the problem you've met was fixed in 0.0.6 though.

Speaking about the installer, it may be the problem for earlier versions, but I've tested it with last releases. Everything updated properly there.

So I would recommend you to fully uninstall your current version and install the new one from this release https://github.com/SpaiR/StrongDMM/releases/tag/v0.0.10

To clarify that everything is fine with that, before you delete the oldest version, just add several new unique tiles and save the map there. You should meet the bug. Then try do the same stuff with the newest release and check the result.

<details>
<summary>(This help btn)</summary>

![image](https://user-images.githubusercontent.com/12721311/65456415-eeb3f880-de51-11e9-96fd-e2c2d5238552.png)


</details>

**Comment by r4d6** [comment] 2019-12-08 00:23
I have the same problem, and it is annoying as hell.

[(https://imgur.com/a/n9CUeYj)]

**Comment by SpaiR** [comment] 2019-12-08 07:31
@r4d6 Could you give me your map file so I would be able to play around with it? And if you have any backup file (with changes before scrambling occurred) it could be helpful too.

**Comment by r4d6** [comment] 2019-12-08 12:17
Two versions with different levels of **scrambling**

[Buggy Map.zip](https://github.com/SpaiR/StrongDMM/files/3936197/Buggy.Map.zip)

**Closed** 2020-04-05 09:02 UTC
Labels: bug, duplicate
