### ISSUE TITLE
select all of a certain type of object

### ISSUE THREAD

**Issue by Xoxeyos** [SpaiR/StrongDMM#9] opened 2019-09-14 01:48 UTC
I am having trouble finding and deleting certain objects on an old map, I think this will be a good quality of life improvement.

**Comment by SpaiR** [comment] 2020-01-28 19:45
Duplicate of the #1 
Will be added in the next release. Demo by the link below
https://imgur.com/a/mq6gotQ

**Closed by SpaiR** 2020-01-28 19:45 UTC
Labels: enhancement
