### ISSUE TITLE
Bug: holding the button when entering Edit... the crash occurs

### ISSUE THREAD

**Issue by SanecMan** [SpaiR/StrongDMM#49] opened 2020-05-22 15:47 UTC
_(translated text from one language to another)_
when trying to delay any button in Edit... (aka VV) when we edit a line, the program crashes. In my case, I changed the health value of the creature and to make it immortal, I held the zero button and got a crash.

**Comment by SpaiR** [comment] 2020-05-22 16:26
Is this a constantly reproducible problem or it was only once? What is the version of the editor do you use?

**Comment by SpaiR** [comment] 2020-05-29 08:06
@SanecMan any updates about the question I've asked about?

**Comment by zeskorion** [comment] 2020-06-13 07:32
I encountered a similar bug. Editing a door bolt button caused my game to crash, several times. Here are the crash liogs
[hs_err_pid1500.log](https://github.com/SpaiR/StrongDMM/files/4774236/hs_err_pid1500.log)
[hs_err_pid3600.log](https://github.com/SpaiR/StrongDMM/files/4774237/hs_err_pid3600.log)
[hs_err_pid4900.log](https://github.com/SpaiR/StrongDMM/files/4774238/hs_err_pid4900.log)
[hs_err_pid4988.log](https://github.com/SpaiR/StrongDMM/files/4774239/hs_err_pid4988.log)
[hs_err_pid8588.log](https://github.com/SpaiR/StrongDMM/files/4774240/hs_err_pid8588.log)
[hs_err_pid16448.log](https://github.com/SpaiR/StrongDMM/files/4774241/hs_err_pid16448.log)
[hs_err_pid16672.log](https://github.com/SpaiR/StrongDMM/files/4774242/hs_err_pid16672.log)
[hs_err_pid17816.log](https://github.com/SpaiR/StrongDMM/files/4774243/hs_err_pid17816.log)
[hs_err_pid17968.log](https://github.com/SpaiR/StrongDMM/files/4774244/hs_err_pid17968.log)

**Comment by SpaiR** [comment] 2020-06-13 09:02
@zeskorion The bug you experience was fixed in v1.3.1. You have v1.3.0. Use the latest version of the editor. To ensure that - start the editor with **[sdmmlauncher program](https://github.com/SpaiR/sdmmlauncher/releases/latest/download/sdmmlauncher.exe)**

DO NOT use zip from the release page directly, since you're increasing chances you'll use an outdated version.

I'm closing the issue, since the bug is unreproducable on the latest version.

**Closed by SpaiR** 2020-06-13 09:02 UTC

**Comment by zeskorion** [comment] 2020-06-13 22:11
> @zeskorion The bug you experience was fixed in v1.3.1. You have v1.3.0. Use the latest version of the editor. To ensure that - start the editor with **[sdmmlauncher program](https://github.com/SpaiR/sdmmlauncher/releases/latest/download/sdmmlauncher.exe)**
> 
> DO NOT use zip from the release page directly, since you're increasing chances you'll use an outdated version.
> 
> I'm closing the issue, since the bug is unreproducable on the latest version.
sick!
